### PR TITLE
Change tab title

### PR DESCRIPTION
**Pull request by trinaldi**
This is very crude and raw, but can it be a rationale to the tab title issue?

### CODE REVIEW

**Comment by AidanSpeakss** [comment]
Apologies, I actually fixed this issue already, in v1.6.3, I just forgot to push the update, you can see how I did it if you check the code now.

**Comment by AidanSpeakss** [comment]
If you are looking for something to work on though, the tab title showing during the load problem is still open. My best idea so far is to use a content script that is always running and modifying the tab titles. I need to work on the FakePII generation option.

**Comment by trinaldi** [comment]
Awesome! I didn't check it, sorry :)

I'll look into this issue!

**Comment by trinaldi** [comment]
I don't think we can avoid the flash.. I tried a lot of things, even straight up `document.title = "":` as the first line. Also MDN/whatwg states: `If the title element is non-null, let element be the title element.`

**Pull request closed without merging**
